#!/usr/bin/env ruby

require "json"
require "yaml"

ROOT = File.expand_path("../..", __dir__)
SOURCE_DIR = File.join(ROOT, "ocd_backend", "sources")
OUTPUT = File.join(ROOT, "woozi", "src", "sources", "catalog.generated.ts")

TYPE_MAP = {
  "municipality" => "gemeente",
  "province" => "provincie",
  "waterschap" => "waterschap",
}.freeze

IMPLEMENTED_SUPPLIERS = %w[notubiz ibabs].freeze

def humanize_key(value)
  value.to_s.split(/[_-]+/).map { |part| part.empty? ? part : part[0].upcase + part[1..] }.join(" ")
end

def resolve_template(value, entry, field_name)
  return value unless value.is_a?(String)

  case value
  when "{key}"
    entry.fetch("key")
  when "{key!c}"
    field_name == "ibabs_sitename" ? entry.fetch("key") : humanize_key(entry.fetch("key"))
  else
    value
  end
end

def normalize_entry(file_name, root_name, entry)
  supplier = entry.fetch("supplier")
  organization_type = TYPE_MAP.fetch(entry.fetch("source_type"))
  key = entry.fetch("key")
  source_name = resolve_template(entry["source_name"], entry, "source_name")

  {
    sourceRef: "#{supplier}:#{organization_type}:#{key}",
    key: key,
    label: source_name || humanize_key(key),
    sourceName: source_name,
    supplier: supplier,
    organizationType: organization_type,
    allmanakId: entry["allmanak_id"],
    cbsId: entry["cbs_id"],
    notubizOrganizationId: entry["notubiz_organization_id"],
    ibabsSitename: resolve_template(entry["ibabs_sitename"], entry, "ibabs_sitename"),
    baseUrl: resolve_template(entry["base_url"], entry, "base_url"),
    sessionId: resolve_template(entry["session_id"], entry, "session_id"),
    legacyConfigFile: file_name,
    legacyConfigRoot: root_name,
    implemented: IMPLEMENTED_SUPPLIERS.include?(supplier),
  }.compact
end

entries = Dir[File.join(SOURCE_DIR, "*.yaml")].sort.flat_map do |file|
  data = YAML.safe_load(File.read(file), aliases: true)
  root = data.keys.find { |key| !key.start_with?("_") }
  next [] unless root

  data.fetch(root).each_with_object([]) do |(_name, entry), result|
    next unless entry.is_a?(Hash)
    result << normalize_entry(File.basename(file), root, entry)
  end
end

entries.sort_by! { |entry| [entry[:supplier], entry[:organizationType], entry[:key]] }

content = <<~TS
  // Generated by scripts/generate_source_catalog.rb from ocd_backend/sources/*.yaml.
  // Do not edit by hand.
  import type { SourceCatalogEntry } from "../types.ts";

  export const sourceCatalog = #{JSON.pretty_generate(entries)} satisfies SourceCatalogEntry[];

  export const sourceCatalogByRef = Object.fromEntries(
    sourceCatalog.map((source) => [source.sourceRef, source]),
  ) as Record<string, SourceCatalogEntry>;
TS

File.write(OUTPUT, content)
puts "Wrote #{OUTPUT} (#{entries.length} sources)"
