/**
 * Sitemaps for search engines (#206).
 *
 * Every meeting and document has an address of its own (`/?view=<id>`), and
 * `robots.txt` invites crawlers, but nothing told them which addresses exist, so
 * a crawler had to find them through search results one by one. This builds
 * `sitemap.xml` as an index with one sitemap per organization, listing the
 * meetings and documents of the last twelve months with a `lastmod` taken from
 * the export log.
 *
 * It is generated by a script (scripts/generate_sitemaps.ts) and stored in
 * object storage; the web container only serves what is there. Walking the
 * export log is far too heavy for a request on the single-threaded server.
 */
import type { ExportChangeRecord } from "../types.ts";

/** The protocol's limit per sitemap file; an index may list as many files. */
export const SITEMAP_MAX_URLS = 50_000;
export const SITEMAP_PREFIX = "sitemaps/";
export const SITEMAP_INDEX_KEY = `${SITEMAP_PREFIX}index.xml`;
export const DEFAULT_PUBLIC_BASE_URL = "https://openbesluitvorming.nl";

export interface SitemapEntry {
  entityId: string;
  /** When the export log last changed the entity. */
  lastmod: string;
  /** The day the entity is about, which is what the window is cut on. */
  date: string;
}

export interface SitemapFile {
  name: string;
  lastmod: string;
  xml: string;
  urlCount: number;
}

/** The date a meeting or document is about, as `YYYY-MM-DD`, the same one the
 * search index sorts on (see `documentReferenceDate` in src/quickwit/project.ts).
 * Undefined when the record carries none or it is not a date. */
export function entityDay(record: ExportChangeRecord): string | undefined {
  const payload = record.payload as
    | { start_date?: string; last_discussed_at?: string; date_modified?: string }
    | undefined;
  const raw =
    record.entity_type === "Meeting"
      ? payload?.start_date
      : (payload?.last_discussed_at ?? payload?.date_modified);
  const day = raw?.trim().slice(0, 10);
  return day && /^\d{4}-\d{2}-\d{2}$/.test(day) ? day : undefined;
}

/** The first day inside a window of `months` months ending at `now`. */
export function windowStart(now: Date, months: number): string {
  const start = new Date(now);
  start.setUTCMonth(start.getUTCMonth() - months);
  return start.toISOString().slice(0, 10);
}

/** Meetings and documents dated on or after `since`, newest change first. */
export function collectSitemapEntries(
  records: Iterable<ExportChangeRecord>,
  since: string,
): SitemapEntry[] {
  const entries: SitemapEntry[] = [];
  for (const record of records) {
    if (record.entity_type !== "Meeting" && record.entity_type !== "Document") {
      continue;
    }
    const date = entityDay(record);
    if (!date || date < since) {
      continue;
    }
    entries.push({ entityId: record.entity_id, lastmod: toLastmod(record.time), date });
  }
  // The id breaks ties so two runs over the same log write the same files.
  entries.sort(
    (a, b) => b.lastmod.localeCompare(a.lastmod) || a.entityId.localeCompare(b.entityId),
  );
  return entries;
}

function toLastmod(time: string): string {
  const parsed = new Date(time);
  return Number.isNaN(parsed.getTime()) ? time : `${parsed.toISOString().slice(0, 19)}Z`;
}

export function entityUrl(baseUrl: string, entityId: string): string {
  return `${baseUrl.replace(/\/+$/, "")}/?view=${encodeURIComponent(entityId)}`;
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

const XML_HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n';

export function renderSitemap(baseUrl: string, entries: SitemapEntry[]): string {
  const urls = entries
    .map(
      (entry) =>
        `<url><loc>${escapeXml(entityUrl(baseUrl, entry.entityId))}</loc>` +
        `<lastmod>${entry.lastmod}</lastmod></url>`,
    )
    .join("\n");
  return (
    `${XML_HEADER}<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${urls}${urls ? "\n" : ""}</urlset>\n`
  );
}

export function renderSitemapIndex(
  baseUrl: string,
  files: Array<{ name: string; lastmod: string }>,
): string {
  const root = baseUrl.replace(/\/+$/, "");
  const items = files
    .map(
      (file) =>
        `<sitemap><loc>${escapeXml(`${root}/${SITEMAP_PREFIX}${file.name}`)}</loc>` +
        `<lastmod>${file.lastmod}</lastmod></sitemap>`,
    )
    .join("\n");
  return (
    `${XML_HEADER}<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${items}${items ? "\n" : ""}</sitemapindex>\n`
  );
}

/** Name of one organization's `part`th file, counting from 1. The pattern is
 * what the web server accepts, so keep the two in step. */
export function sitemapFileName(sourceKey: string, part: number): string {
  return `${sourceKey}-${part}.xml`;
}

export const SITEMAP_FILE_PATTERN = /^[a-z0-9_-]+-\d+\.xml$/;

/** One organization's entries as sitemap files of at most `maxUrls` addresses.
 * An organization with nothing in the window produces no file. */
export function buildSourceSitemaps(
  baseUrl: string,
  sourceKey: string,
  entries: SitemapEntry[],
  maxUrls = SITEMAP_MAX_URLS,
): SitemapFile[] {
  const files: SitemapFile[] = [];
  for (let start = 0; start < entries.length; start += maxUrls) {
    const slice = entries.slice(start, start + maxUrls);
    files.push({
      name: sitemapFileName(sourceKey, files.length + 1),
      lastmod: slice[0].lastmod,
      xml: renderSitemap(baseUrl, slice),
      urlCount: slice.length,
    });
  }
  return files;
}
